[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "lirics"
description = "Software for liquid ring machine modelling adn design"

classifiers = [
    "Development Status :: 1 - Planning",

    "Intended Audience :: Science/Research",
    "Intended Audience :: Education",
    "Intended Audience :: Manufacturing",

    "Topic :: Scientific/Engineering",

    "Programming Language :: Python :: 3.13",
]

readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]

authors = [{ name = "Amir Aslanov", email = "amiraslanov16@gmail.com" }]
maintainers = [{ name = "Amir Aslanov", email = "amiraslanov16@gmail.com" }]

requires-python = ">= 3.13"
dependencies = ["numpy", "scipy", "matplotlib"]

dynamic = ["version"]

[project.urls]
repository = "https://github.com/smwrdthing/lirics"
